analysis/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^home$', views.home, name='home'),
    url(r'^education$', views.education, name='education'),

]

project_job/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('analysis.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

analysis/forms.py
from django import forms
from .models import UserInfo
from django.forms import formset_factory
from django.forms.formsets import BaseFormSet
from django.contrib import messages
from .models import PostGraduateCourse, UnderGraduateCourse



class DateInput(forms.DateInput):
    input_type = 'date'

class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = [
            'fname',
            'lname',
            'dob',
            'place_of_birth',
            'image',
        ]
        widgets = {
            'dob': DateInput(),
        }

class EducationForm(forms.Form):
    '''highschool = forms.CharField(widget=forms.Textarea, max_length=500)
    intermediate = forms.CharField(widget=forms.Textarea, max_length=500)
    graduation = forms.CharField(widget=forms.Textarea, max_length=500)
    post_garduation = forms.CharField(widget=forms.Textarea, max_length=500)

'''

    # ug = UnderGraduateCourse.objects.all()
    # ug_choices = tuple([college.courses, college.courses] for college in ug)
    #
    # pg = PostGraduateCourse.objects.all()
    # pg_choices = tuple([college.courses, college.courses] for college in pg)

    ten_board = forms.CharField(max_length=100)
    ten_percent = forms.IntegerField(max_value=100)
    ten_file = forms.FileField()

    # Board12 = forms.CharField(max_length=100)
    # Percent12 = forms.IntegerField()
    File12 = forms.FileField()
    # Subject12 = forms.Textarea()
    # MarksScored12 = forms.Textarea()
    # MaximumMarks12 = forms.Textarea()
    # twelve_plus = forms.CharField(widget=forms.Textarea, max_length=500)
    # twelve_minus = forms.CharField(widget=forms.Textarea, max_length=500)

    g_board = forms.CharField(max_length=100)
    g_percent = forms.IntegerField(max_value=100)
    g_file = forms.FileField()

    pg_board = forms.CharField(max_length=100)
    pg_percent = forms.IntegerField(max_value=100)
    pg_file = forms.FileField()

templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="/static/css/educational.css" />
</head>

<body>

    <div id="content">
    {% load staticfiles %}

    {% block content %}{% endblock %}
    </div>


</body>

</html>

templates/educational.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="/static/css/add.css">

  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
  <script type="text/javascript">
var app = angular.module('app', []);
app.controller('formCtrl', function($scope){
  $scope.requestedData = [
    {confirmed: false, subject: '', marks: '', mmarks: ''}
  ];
  $scope.agregarCampos = function () {
    $scope.requestedData.push({confirmed: false, subject: '', marks: '', mmarks: ''});
  };
  $scope.removerCampos = function () {
    var i = this.$index;
    $scope.requestedData.splice(i,1);
  };
});
  </script>

     <script>
       $(document).ready(function(){
     $('.insert-more').click(function() {
           $("#mytable").append("<tr><th><input type='text' id='id_Subject12' placeholder='Subject' name='Subject12[]'></th>"+
           "<th><input type='number' 'id_MarksScored12' placeholder='Marks Scored' name='MarksScored12[]'></th>"+
           "<th><input type='number' id='id_MaximumMarks12' placeholder='Maximum Marks' name='MaximumMarks12[]'></th>"+
           "<th><input type='button' id='id_Remove12' class='remove' style='width: 40px; height: 40px; border-radius: 50%;color: #fff;"+
           "font-size: 20px;background: #D32F2F;' value='&times'></th></tr>");

     });


});
  </script>


</head>
<body>


<section ng-app="app" ng-controller="formCtrl" class="module">
  <form method="post" role="form" novalidate action="" enctype="multipart/form-data">
      {% csrf_token %}

<div>

  <h1>10th Standard</h1>
  <table style="width:100%">
  <tr>
    <td align="center"><label>Board:</label></td>
    <td align="center"><input type="text" id="id_ten_board" name="ten_board"  placeholder="Enter Your Board" ng-model="board10" ng-disabled="checked" ng-required="true"></td>
  </tr>
  <tr>
    <td align="center"><label>Percentage:</label></td>
    <td align="center"><input type="number" id="id_ten_percent" name="ten_percent" placeholder="Percentage/GPA" ng-model="percentage10" ng-disabled="checked" ng-required="true"></td>

   </tr>
   <tr>
        <td align="center"><label for="fileName">Select a file</label></td>
          <td align="center">
          <!--<input id="uploadFile" placeholder="Choose File" disabled="disabled" />
          <div class="fileUpload btn btn-primary">
              <span>Upload</span>
              <input id="uploadBtn" type="file" class="upload" />
          </div>-->
          <input id="id_ten_file" name="ten_file" value="{{ current_name }}" type='file' class="upload" />
          </td>


   </tr>
  </table>
  </div>

<div>
  <h1>12th standard</h1>
  <table style="width:100%">
  <tr>
    <td align="center"><label>Board:</label></td>
    <td align="center"><input type="text" id="id_Board12" name="Board12" placeholder="Enter Your Board" ng-model="board" ng-disabled="checked" ng-required="true"></td>
  </tr>
  <tr>
    <td align="center"><label>Percentage:</label></td>
    <td align="center"><input type="text" name="Percent12" id="id_Percent12" placeholder="Percentage/GPA" ng-model="percentage" ng-disabled="checked" ng-required="true"></td>

   </tr>
   <tr>
        <td align="center"><label for="fileName">Select a file</label></td>
          <td align="center">
          <input id="id_File12" name="File12" type="file" class="upload" />
          </td>


   </tr>
  </table>


    <ul style="list-style:none;">
      <li>

    <table id="mytable">
    <tr>
        <th><input type="text" id='id_Subject12' placeholder="Subject" name="Subject12[]"></th>

        <th><input type="number" id='id_MarksScored12' placeholder="Marks Scored" name="MarksScored12[]"></th>
        <th><input type="number" id='id_MaximumMarks12' placeholder="Maximum Marks" name="MaximumMarks12[]"></th>

        <th><input type="button" id='id_Remove12' name="Remove12" class="remove" style="width: 40px; height: 40px; border-radius: 50%; color: #fff; font-size: 20px; background: #D32F2F;" value="&times;"></th>

        <th><input type="button" id='id_Add12' name="Add12" ng-model="checked" class="insert-more" style="width: 40px; height: 40px; border-radius: 50%; color: #fff; font-size: 20px; background: #6495ed;" value="+"></th>
        </tr>
        </table>
      </li>
    </ul>
</div>



<div>
  <h1>Graduation</h1>
  <table style="width:100%">
  <tr>
    <td align="center"><label>Course:</label></td>
    <td>
        <select name="g_board" id="id_g_board" >
            {% for x in g %}
                <option value="{{ x }}"> {{ x }}</option>
            {% endfor %}
        </select>

    </td>
  </tr>
  <tr>
    <td align="center"><label>Percentage:</label></td>
    <td align="center"><input id="id_g_percent" name="g_percent" type="text" placeholder="Percentage/GPA" ng-model="grpercentage" ></td>

   </tr>
   <tr>
        <td align="center"><label for="fileName">Select a file</label></td>
          <td align="center">
          <input id="id_g_file" name="g_file" type="file" class="upload" />
          </td>


   </tr>
  </table>
  </div>


<div>
  <h1>Post Graduation</h1>
  <table style="width:100%">
  <tr>
    <td align="center"><label>Course:</label></td>
    <td align="center">
        <select name="pg_board" id="id_pg_board" >
            {% for x in pg %}
                <option value="{{ x }}"> {{ x }}</option>
            {% endfor %}
        </select>
    </td>
  </tr>
  <tr>
    <td align="center"><label>Percentage:</label></td>
    <td align="center"><input id="id_pg_percent" name="pg_percent" type="text" placeholder="Percentage/GPA" ng-model="percentage" ></td>

   </tr>
   <tr>
        <td align="center"><label for="fileName">Select a file</label></td>
          <td align="center">
          <input id="id_pg_file" name="pg_file" type="file" class="upload" />
          </td>


   </tr>
  </table>
  </div>


      <input class="btn btn-primary" type="submit" value="submit">Submit</input>

    </form>
  
  
</section>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

    Kindly fill the details!</h1>

    <form method="post" action="" enctype="multipart/form-data">

    {% csrf_token %}
    {{ form.as_p }}

        <input type="submit" value="Submit" />


    </form>
{% endblock %}